
server:
  port: 8085



spring:
  application:
    name: REPORT-GENERATION-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka